<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function css_emimage_help($path, $arg) {
  switch ($path) {
    case 'admin/help#css_emimage':
      $output = '<p>'. t('Replaces image URLs in aggregated CSS files with embedded images when <em>CSS optimization</em> has been enabled in the <a href="@performance">Performance settings</a>.', array('@performance' => url('admin/settings/performance'))) .'</p>';
      return $output;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function css_emimage_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'system_performance_settings') {
    $form['bandwidth_optimizations']['preprocess_css']['#description'] .= t(' Once the CSS files have been aggregated, image URLs will be replaced with embedded images.');
    $form['bandwidth_optimizations']['css_emimage_ielimit'] = array(
      '#type' => 'checkbox',
      '#title' => t('Only embed images less than 32KB'),
      '#description' => t('Internet Explorer does not support embedded images larger than 32KB. If you are not concerned about IE support you can ignore this limitation; otherwise, it is best to leave this checked.'),
      '#default_value' => variable_get('css_emimage_ielimit', 1),
      '#weight' => $form['bandwidth_optimizations']['preprocess_css']['#weight'] + .1,
    );
  }
}

/**
 * Implementation of hook_theme_registry_alter().
 * 
 * Make css_emimage's page preprocess function run after everything else.
 * If the css_gzip module is installed, move it's preprocess function after ours.
 */
function css_emimage_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['page'])) {
    // Move our preprocess function after everything else.
    if ($key = array_search('css_emimage_preprocess_page', $theme_registry['page']['preprocess functions'])) {
      unset($theme_registry['page']['preprocess functions'][$key]);
    }
    $theme_registry['page']['preprocess functions'][] = 'css_emimage_preprocess_page';
    // Move css_gzip's preprocess function after ours.
    if ($key = array_search('css_gzip_preprocess_page', $theme_registry['page']['preprocess functions'])) {
      unset($theme_registry['page']['preprocess functions'][$key]);
      $theme_registry['page']['preprocess functions'][] = 'css_gzip_preprocess_page';
    }
  } 
}

/**
 * Implementation of hook_preprocess_hook().
 * 
 * Replace URLs with data URIs in aggregated CSS files if CSS optimization is turned on.
 */
function css_emimage_preprocess_page(&$variables) {
  if (!empty($variables['styles']) && variable_get('preprocess_css', 0)) {
    $variables['styles'] = _css_emimage_process($variables['styles']);
  }
}

/**
 * Helper function to replace URLs with data URIs.
 */
function _css_emimage_process($styles) {
  $path_to_files_directory = base_path() . file_directory_path();
  $pattern = '/<link(.*?)href="' . preg_quote($path_to_files_directory, '/') . '(.*?)"(.*?)\\/>/';
  if (preg_match_all($pattern, $styles, $matches) > 0) {
    foreach ($matches[2] as $i => $aggregated_file_name) {
      $aggregated_file_path = file_directory_path() . $aggregated_file_name;
      $emimage_file_name = str_replace('.css', '.emimage.css', $aggregated_file_name);
      $emimage_file_path = file_directory_path() . $emimage_file_name;
      
      // Save the processed CSS file if it doesn't exist yet
      if (!file_exists($emimage_file_path)) {
        _css_emimage_collect(null, null, true);
        $contents = file_get_contents(file_directory_path() . $aggregated_file_name);
        $contents = preg_replace_callback('/([^}\\r\\n]+){[^{}]+(background|background-image|list-style|list-style-image):[^{}]*(url\([\'"]?'. preg_quote(base_path(), '/') .'([^\'")]+)[\'"]?\))[^{}]*}/i', '_css_emimage_replace', $contents);
        
        $datauri_css = '';
        foreach (_css_emimage_collect() as $data) {
          foreach ($data['css'] as $property => $selectors) {
            $datauri_css .= implode(',', $selectors) .'{'. $property .':'. $data['datauri'] .";}\n";
            // Overrides for IE6 and IE7
            foreach ($selectors as $i => $selector) {
              $prefix = 'html ';
              if (strpos($selector, 'html') === 0) {
                $prefix = '';
              }
              $datauri_css .= " * $prefix$selector {". $property .':'. $data['url'] .";}\n";
              $datauri_css .= " *+$prefix$selector {". $property .':'. $data['url'] .";}\n";
            }
          }
        }
        
        // TODO option to save to one file or multiple files
        
        // Save the contents to the new CSS file
        // $datauri_css may be empty, but we use the file as a flag to
        // prevent processing the CSS on every uncached request
        file_save_data($contents, $aggregated_file_path, FILE_EXISTS_REPLACE);
        file_save_data($datauri_css, $emimage_file_path, FILE_EXISTS_REPLACE);
      }
      
      // Replace the aggregated file with the processed CSS file
      if (file_exists($emimage_file_path) && filesize($emimage_file_path)) {
        $styles = str_replace($matches[0][$i], $matches[0][$i] ."\n". str_replace($aggregated_file_name, $emimage_file_name, $matches[0][$i]), $styles);
      }
    }
  }
  
  return $styles;
}

/**
 * preg_replace_callback() callback to replace URLs with data URIs.
 */
function _css_emimage_replace($matches) {
  list($declaration, $selector, $property, $url, $file) = $matches;
  if ($image = image_get_info($file)) {
    $ielimit = variable_get('css_emimage_ielimit', 1); // only embed images less than 32KB, thanks IE
    if (!$ielimit || ($ielimit && ($image['file_size']*1.3333) < 32768)) {
      $declaration = str_replace($url, 'none', $declaration);
      _css_emimage_collect($matches, $image);
    }
  }
  return $declaration;
}

/**
 * Helper function to collect CSS declarations to replace with data URIs.
 */
function _css_emimage_collect($matches = NULL, $image = NULL, $reset = FALSE) {
  static $data = array();
  if ($reset) {
    $data = array();
  }
  if (is_null($matches)) {
    return $data;
  }
  
  if (is_array($matches) && is_array($image)) {
    list($declaration, $selector, $property, $url, $file) = $matches;
    // Create the data URI
    if (!isset($data[$file]['datauri'])) {
      $data[$file]['datauri'] = 'url(data:'. $image['mime_type'] .';base64,'. base64_encode(file_get_contents($file)). ')';
      $data[$file]['url'] = $url;
    }
    // Normalize the CSS property name so we can collapse as many declarations as possible
    if ($property == 'background' || $property == 'list-style') {
      $property .= '-image';
    }
    $data[$file]['css'][$property][] = $selector;
  }
  
  return $data;
}
